name: Build site

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Merge main -> gh-pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git merge origin/main -Xtheirs --allow-unrelated-histories

      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install dependencies 
        run: npm install

      - name: Build site
        run: npm run build

      - name: Commit and push
        run: |
          git add -f dist
          git commit -m "build site for ${{ github.sha }}" || :
          git push
